title: Modellen | Netbeheer Nederland
description: Documentatie van informatiemodellen en begrippen.

remote_theme: just-the-docs/just-the-docs

search_enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
fav_icon: "/assets/images/favicon.png"

nav_external_links:
  - title: Begrippen
    url: https://modellen.netbeheernederland.nl/begrippen
    hide_icon: true
  - title: Registers
    url: https://modellen.netbeheernederland.nl/stelsel
    hide_icon: true
  - title: Dataproducten
    url: https://modellen.netbeheernederland.nl/docs-new
