title: Modellen | Netbeheer Nederland
description: Documentatie van informatiemodellen en begrippen.

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: false

color_scheme: nbnl
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.png"

callouts:
  note:
    color: purple
